language: node_js

node_js:
  - "node"
  
install:
  - npm install

script:
  - npm test

notifications:
  email:
    recipients:
      - joaorob.m.l@gmail.com
    on_success: always
    on_failure: always
